INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('1', '¿Cuál es la lengua oficial de Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('1', '¿Cuál es el departamento más poblado de Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('1', '¿Con qué océanos limita Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('1', '¿Cómo se llama el aeropuerto de Bogotá?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('1', '¿Cuál es la flor nacional de Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('2', '¿Principal puerto de Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('2', '¿Qué colombiano escribió la famosa novela romántica María?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('2', '¿Cuál es el lago más grande de Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('2', '¿Quién fundo la ciudad de Santa Fe de Bogotá?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('2', '¿Cuál es la capital de Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('3', '¿Cuál es el diario de mayor circulación en Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('3', '¿En qué municipio se encuentra la catarata del Salto del Tequendama?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('3', '¿Qué ciudad colombiana se conoce por ser la capital mundial de la salsa?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('3', '¿Qué río situado en la serranía de la Macarena posee un lecho que cambia de color?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('3', '¿En qué ciudad colombiana se encuentra la Ciudad Perdida?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('4', '¿Con qué país conformó Colombia la República de Nueva Granada (1832-1858)?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('4', '¿Qué confrontación surge en reacción a la presidencia conservadora de Manuel Antonio Sanclemente?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('4', '¿Cuántas divisiones políticas-administrativas posee Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('4', '¿Cuál es el denominado “pueblito más lindo de Colombia”, designado monumento nacional?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('4', '¿Cuál es la denominada “capital latinoamericana del grafiti”?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('5', '¿En qué ciudad se celebra anualmente la conocida “Feria de las Flores”?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('5', '¿En qué deporte obtuvo Colombia su primer título mundial en 1947?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('5', '¿Cuántas vertientes hidrográficas hay en Colombia?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('5', '¿En qué departamento se encuentra el parque eólico Jepirachi?');
INSERT INTO `juego_preguntas`.`preguntas` (`categoria_pregunta`, `pregunta`) VALUES ('5', '¿Cuál es el grupo indígena más numeroso de Colombia?');