INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'A. Inglés', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'B. Mandarín', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'B. Mandarín', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'C. Español', b'1', '5000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('1', 'D. Portugués', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'A. Cundinamarca', b'1', '5000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'B. Antioquia', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'C. Norte de Santander', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('2', 'D. Amazonas', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'A. Pacífico y el Atlántico', b'1', '5000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'B. Atlántico e Índico', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'C. Índico y Pacífico', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('3', 'D. Antártico y Atlántico', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'A. Aeropuerto Eustorgio Colmenares', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'B. Aeropuerto Internacional el Dorado', b'1', '5000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'C. Aeropuerto Camilo Daza', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('4', 'D. Aeropuerto José María Córdoba', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'A. Claveles', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'B. Tulipán', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'C. Orquídea', b'1', '5000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('5', 'D. Girasol', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'A. Puerto de Buenaventura', b'1', '10000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'B. Puerto Colombia', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'C. Puerto Santander', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('6', 'D. Puerto de Tumaco', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'A. Jorge Isaacs', b'1', '10000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'B. Gabriel García Márquez', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'C. Rafael Pombo', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('7', 'D. Santiago Gamboa', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'A. Ciénaga de Zapatosa', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'B. Laguna de la Cocha', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'C. Lago de Tota', b'1', '10000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('8', 'D. Ciénaga Grande de Santa Marta', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'A. Pedro de Heredia', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'B. Gonzalo Jiménez de Quesada', b'1', '10000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'C. Sebastián de Belalcázar', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('9', 'D. Nicolás de Federmán', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'A. Medellín', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'B. Cali', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'C. Barranquilla', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('10', 'D. Bogotá', b'1', '10000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'A. Diario La Opinión', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'B. El Espectador', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'C. Revista Semana', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('11', 'D. El Tiempo', b'1', '20000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'A. Soacha', b'1', '20000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'B. Chía', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'C. Chapinero', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('12', 'D. Arauca', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'A. Villavicencio', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'B. Cartagena', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'C. Cali', b'1', '20000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('13', 'D. Manizales', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'A. Río Caño Cristales', b'1', '20000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'B. Río Magdalena', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'C. Río Amazonas', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('14', 'D. Río Casanare', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'A. Barranquilla', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'B. Cartagena', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'C. Santa Marta', b'1', '20000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('15', 'D. Villavicencio', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'A. Venezuela', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'B. Panamá', b'1', '50000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'D. México', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('16', 'E. Bolivia', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'A. La guerra de los mil días', b'1', '50000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'B. La guerra fría', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'C. La guerra de los supremos', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('17', 'D. La guerra magna', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'A. 45', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'B. 32', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'C. 33', b'1', '50000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('18', 'D. 27', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'A. Barichara', b'1', '50000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'B. Santa fe de Antioquia', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'C. Jardín', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('19', 'D. Mompós', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'A. Medellín', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'B. Cali', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'C. Barranquilla', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('20', 'D. Bogotá', b'1', '50000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'A. Bogotá', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'B. Valledupar', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'C. Medellín', b'1', '100000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('21', 'D. Cali', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'A. Fútbol', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'B. Natación', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'C. Patinaje', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('22', 'D. Béisbol', b'1', '100000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'A. 12', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'B. 4', b'1', '100000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'C. 10', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('23', 'D. 8', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'A. Santander', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'B. Antioquia', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'C. Guajira', b'1', '100000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('24', 'D. Huila', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'A. Grupo indígena Chimila', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'B. Grupo indígena yuco yukpa', b'0', '0');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'C. Grupo indígena Wayuu', b'1', '100000');
INSERT INTO `juego_preguntas`.`respuestas` (`id_pregunta`, `respuesta`, `respuesta_correcta`, `puntuacion_respuesta`) VALUES ('25', 'D. Grupo indígena nukak makú', b'0', '0');